// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceListProjectObjectsReader is a Reader for the KafeidoServiceListProjectObjects structure.
type KafeidoServiceListProjectObjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceListProjectObjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceListProjectObjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceListProjectObjectsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceListProjectObjectsOK creates a KafeidoServiceListProjectObjectsOK with default headers values
func NewKafeidoServiceListProjectObjectsOK() *KafeidoServiceListProjectObjectsOK {
	return &KafeidoServiceListProjectObjectsOK{}
}

/*
KafeidoServiceListProjectObjectsOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceListProjectObjectsOK struct {
	Payload *models.KafeidoListProjectObjectsResponse
}

// IsSuccess returns true when this kafeido service list project objects o k response has a 2xx status code
func (o *KafeidoServiceListProjectObjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service list project objects o k response has a 3xx status code
func (o *KafeidoServiceListProjectObjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service list project objects o k response has a 4xx status code
func (o *KafeidoServiceListProjectObjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service list project objects o k response has a 5xx status code
func (o *KafeidoServiceListProjectObjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service list project objects o k response a status code equal to that given
func (o *KafeidoServiceListProjectObjectsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service list project objects o k response
func (o *KafeidoServiceListProjectObjectsOK) Code() int {
	return 200
}

func (o *KafeidoServiceListProjectObjectsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/objects][%d] kafeidoServiceListProjectObjectsOK %s", 200, payload)
}

func (o *KafeidoServiceListProjectObjectsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/objects][%d] kafeidoServiceListProjectObjectsOK %s", 200, payload)
}

func (o *KafeidoServiceListProjectObjectsOK) GetPayload() *models.KafeidoListProjectObjectsResponse {
	return o.Payload
}

func (o *KafeidoServiceListProjectObjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoListProjectObjectsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKafeidoServiceListProjectObjectsDefault creates a KafeidoServiceListProjectObjectsDefault with default headers values
func NewKafeidoServiceListProjectObjectsDefault(code int) *KafeidoServiceListProjectObjectsDefault {
	return &KafeidoServiceListProjectObjectsDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceListProjectObjectsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceListProjectObjectsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service list project objects default response has a 2xx status code
func (o *KafeidoServiceListProjectObjectsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service list project objects default response has a 3xx status code
func (o *KafeidoServiceListProjectObjectsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service list project objects default response has a 4xx status code
func (o *KafeidoServiceListProjectObjectsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service list project objects default response has a 5xx status code
func (o *KafeidoServiceListProjectObjectsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service list project objects default response a status code equal to that given
func (o *KafeidoServiceListProjectObjectsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service list project objects default response
func (o *KafeidoServiceListProjectObjectsDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceListProjectObjectsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/objects][%d] KafeidoService_ListProjectObjects default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListProjectObjectsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/objects][%d] KafeidoService_ListProjectObjects default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListProjectObjectsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceListProjectObjectsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
