// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceCreateDataSourceParams creates a new KafeidoServiceCreateDataSourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceCreateDataSourceParams() *KafeidoServiceCreateDataSourceParams {
	return &KafeidoServiceCreateDataSourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceCreateDataSourceParamsWithTimeout creates a new KafeidoServiceCreateDataSourceParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceCreateDataSourceParamsWithTimeout(timeout time.Duration) *KafeidoServiceCreateDataSourceParams {
	return &KafeidoServiceCreateDataSourceParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceCreateDataSourceParamsWithContext creates a new KafeidoServiceCreateDataSourceParams object
// with the ability to set a context for a request.
func NewKafeidoServiceCreateDataSourceParamsWithContext(ctx context.Context) *KafeidoServiceCreateDataSourceParams {
	return &KafeidoServiceCreateDataSourceParams{
		Context: ctx,
	}
}

// NewKafeidoServiceCreateDataSourceParamsWithHTTPClient creates a new KafeidoServiceCreateDataSourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceCreateDataSourceParamsWithHTTPClient(client *http.Client) *KafeidoServiceCreateDataSourceParams {
	return &KafeidoServiceCreateDataSourceParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceCreateDataSourceParams contains all the parameters to send to the API endpoint

	for the kafeido service create data source operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceCreateDataSourceParams struct {

	// Body.
	Body KafeidoServiceCreateDataSourceBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service create data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateDataSourceParams) WithDefaults() *KafeidoServiceCreateDataSourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service create data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateDataSourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) WithTimeout(timeout time.Duration) *KafeidoServiceCreateDataSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) WithContext(ctx context.Context) *KafeidoServiceCreateDataSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) WithHTTPClient(client *http.Client) *KafeidoServiceCreateDataSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) WithBody(body KafeidoServiceCreateDataSourceBody) *KafeidoServiceCreateDataSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) SetBody(body KafeidoServiceCreateDataSourceBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) WithProjectID(projectID string) *KafeidoServiceCreateDataSourceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido service create data source params
func (o *KafeidoServiceCreateDataSourceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceCreateDataSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
