// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceListAPIKeysReader is a Reader for the KafeidoServiceListAPIKeys structure.
type KafeidoServiceListAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceListAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceListAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceListAPIKeysDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceListAPIKeysOK creates a KafeidoServiceListAPIKeysOK with default headers values
func NewKafeidoServiceListAPIKeysOK() *KafeidoServiceListAPIKeysOK {
	return &KafeidoServiceListAPIKeysOK{}
}

/*
KafeidoServiceListAPIKeysOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceListAPIKeysOK struct {
	Payload *models.AppkafeidoListAPIKeysResponse
}

// IsSuccess returns true when this kafeido service list Api keys o k response has a 2xx status code
func (o *KafeidoServiceListAPIKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service list Api keys o k response has a 3xx status code
func (o *KafeidoServiceListAPIKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service list Api keys o k response has a 4xx status code
func (o *KafeidoServiceListAPIKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service list Api keys o k response has a 5xx status code
func (o *KafeidoServiceListAPIKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service list Api keys o k response a status code equal to that given
func (o *KafeidoServiceListAPIKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service list Api keys o k response
func (o *KafeidoServiceListAPIKeysOK) Code() int {
	return 200
}

func (o *KafeidoServiceListAPIKeysOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/apikey][%d] kafeidoServiceListApiKeysOK %s", 200, payload)
}

func (o *KafeidoServiceListAPIKeysOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/apikey][%d] kafeidoServiceListApiKeysOK %s", 200, payload)
}

func (o *KafeidoServiceListAPIKeysOK) GetPayload() *models.AppkafeidoListAPIKeysResponse {
	return o.Payload
}

func (o *KafeidoServiceListAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppkafeidoListAPIKeysResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKafeidoServiceListAPIKeysDefault creates a KafeidoServiceListAPIKeysDefault with default headers values
func NewKafeidoServiceListAPIKeysDefault(code int) *KafeidoServiceListAPIKeysDefault {
	return &KafeidoServiceListAPIKeysDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceListAPIKeysDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceListAPIKeysDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service list Api keys default response has a 2xx status code
func (o *KafeidoServiceListAPIKeysDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service list Api keys default response has a 3xx status code
func (o *KafeidoServiceListAPIKeysDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service list Api keys default response has a 4xx status code
func (o *KafeidoServiceListAPIKeysDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service list Api keys default response has a 5xx status code
func (o *KafeidoServiceListAPIKeysDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service list Api keys default response a status code equal to that given
func (o *KafeidoServiceListAPIKeysDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service list Api keys default response
func (o *KafeidoServiceListAPIKeysDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceListAPIKeysDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/apikey][%d] KafeidoService_ListApiKeys default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListAPIKeysDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/apikey][%d] KafeidoService_ListApiKeys default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListAPIKeysDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceListAPIKeysDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
