// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceListModelInferenceJobReader is a Reader for the KafeidoServiceListModelInferenceJob structure.
type KafeidoServiceListModelInferenceJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceListModelInferenceJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceListModelInferenceJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceListModelInferenceJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceListModelInferenceJobOK creates a KafeidoServiceListModelInferenceJobOK with default headers values
func NewKafeidoServiceListModelInferenceJobOK() *KafeidoServiceListModelInferenceJobOK {
	return &KafeidoServiceListModelInferenceJobOK{}
}

/*
KafeidoServiceListModelInferenceJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceListModelInferenceJobOK struct {
	Payload *models.KafeidoListModelInferenceJobResponse
}

// IsSuccess returns true when this kafeido service list model inference job o k response has a 2xx status code
func (o *KafeidoServiceListModelInferenceJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service list model inference job o k response has a 3xx status code
func (o *KafeidoServiceListModelInferenceJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service list model inference job o k response has a 4xx status code
func (o *KafeidoServiceListModelInferenceJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service list model inference job o k response has a 5xx status code
func (o *KafeidoServiceListModelInferenceJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service list model inference job o k response a status code equal to that given
func (o *KafeidoServiceListModelInferenceJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service list model inference job o k response
func (o *KafeidoServiceListModelInferenceJobOK) Code() int {
	return 200
}

func (o *KafeidoServiceListModelInferenceJobOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeidoServiceListModelInferenceJobOK %s", 200, payload)
}

func (o *KafeidoServiceListModelInferenceJobOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeidoServiceListModelInferenceJobOK %s", 200, payload)
}

func (o *KafeidoServiceListModelInferenceJobOK) GetPayload() *models.KafeidoListModelInferenceJobResponse {
	return o.Payload
}

func (o *KafeidoServiceListModelInferenceJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoListModelInferenceJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoServiceListModelInferenceJobDefault creates a KafeidoServiceListModelInferenceJobDefault with default headers values
func NewKafeidoServiceListModelInferenceJobDefault(code int) *KafeidoServiceListModelInferenceJobDefault {
	return &KafeidoServiceListModelInferenceJobDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceListModelInferenceJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceListModelInferenceJobDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service list model inference job default response has a 2xx status code
func (o *KafeidoServiceListModelInferenceJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service list model inference job default response has a 3xx status code
func (o *KafeidoServiceListModelInferenceJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service list model inference job default response has a 4xx status code
func (o *KafeidoServiceListModelInferenceJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service list model inference job default response has a 5xx status code
func (o *KafeidoServiceListModelInferenceJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service list model inference job default response a status code equal to that given
func (o *KafeidoServiceListModelInferenceJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service list model inference job default response
func (o *KafeidoServiceListModelInferenceJobDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceListModelInferenceJobDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] KafeidoService_ListModelInferenceJob default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListModelInferenceJobDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] KafeidoService_ListModelInferenceJob default %s", o._statusCode, payload)
}

func (o *KafeidoServiceListModelInferenceJobDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceListModelInferenceJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
