// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceDeleteProjectReader is a Reader for the KafeidoServiceDeleteProject structure.
type KafeidoServiceDeleteProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceDeleteProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceDeleteProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceDeleteProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceDeleteProjectOK creates a KafeidoServiceDeleteProjectOK with default headers values
func NewKafeidoServiceDeleteProjectOK() *KafeidoServiceDeleteProjectOK {
	return &KafeidoServiceDeleteProjectOK{}
}

/*
KafeidoServiceDeleteProjectOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceDeleteProjectOK struct {
	Payload models.KafeidoDeleteProjectResponse
}

// IsSuccess returns true when this kafeido service delete project o k response has a 2xx status code
func (o *KafeidoServiceDeleteProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service delete project o k response has a 3xx status code
func (o *KafeidoServiceDeleteProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service delete project o k response has a 4xx status code
func (o *KafeidoServiceDeleteProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service delete project o k response has a 5xx status code
func (o *KafeidoServiceDeleteProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service delete project o k response a status code equal to that given
func (o *KafeidoServiceDeleteProjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service delete project o k response
func (o *KafeidoServiceDeleteProjectOK) Code() int {
	return 200
}

func (o *KafeidoServiceDeleteProjectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}][%d] kafeidoServiceDeleteProjectOK %s", 200, payload)
}

func (o *KafeidoServiceDeleteProjectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}][%d] kafeidoServiceDeleteProjectOK %s", 200, payload)
}

func (o *KafeidoServiceDeleteProjectOK) GetPayload() models.KafeidoDeleteProjectResponse {
	return o.Payload
}

func (o *KafeidoServiceDeleteProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoServiceDeleteProjectDefault creates a KafeidoServiceDeleteProjectDefault with default headers values
func NewKafeidoServiceDeleteProjectDefault(code int) *KafeidoServiceDeleteProjectDefault {
	return &KafeidoServiceDeleteProjectDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceDeleteProjectDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceDeleteProjectDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service delete project default response has a 2xx status code
func (o *KafeidoServiceDeleteProjectDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service delete project default response has a 3xx status code
func (o *KafeidoServiceDeleteProjectDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service delete project default response has a 4xx status code
func (o *KafeidoServiceDeleteProjectDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service delete project default response has a 5xx status code
func (o *KafeidoServiceDeleteProjectDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service delete project default response a status code equal to that given
func (o *KafeidoServiceDeleteProjectDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service delete project default response
func (o *KafeidoServiceDeleteProjectDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceDeleteProjectDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}][%d] KafeidoService_DeleteProject default %s", o._statusCode, payload)
}

func (o *KafeidoServiceDeleteProjectDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}][%d] KafeidoService_DeleteProject default %s", o._statusCode, payload)
}

func (o *KafeidoServiceDeleteProjectDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceDeleteProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
