// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceGetUserParams creates a new KafeidoServiceGetUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceGetUserParams() *KafeidoServiceGetUserParams {
	return &KafeidoServiceGetUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceGetUserParamsWithTimeout creates a new KafeidoServiceGetUserParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceGetUserParamsWithTimeout(timeout time.Duration) *KafeidoServiceGetUserParams {
	return &KafeidoServiceGetUserParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceGetUserParamsWithContext creates a new KafeidoServiceGetUserParams object
// with the ability to set a context for a request.
func NewKafeidoServiceGetUserParamsWithContext(ctx context.Context) *KafeidoServiceGetUserParams {
	return &KafeidoServiceGetUserParams{
		Context: ctx,
	}
}

// NewKafeidoServiceGetUserParamsWithHTTPClient creates a new KafeidoServiceGetUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceGetUserParamsWithHTTPClient(client *http.Client) *KafeidoServiceGetUserParams {
	return &KafeidoServiceGetUserParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceGetUserParams contains all the parameters to send to the API endpoint

	for the kafeido service get user operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceGetUserParams struct {

	// UserID.
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceGetUserParams) WithDefaults() *KafeidoServiceGetUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceGetUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) WithTimeout(timeout time.Duration) *KafeidoServiceGetUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) WithContext(ctx context.Context) *KafeidoServiceGetUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) WithHTTPClient(client *http.Client) *KafeidoServiceGetUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) WithUserID(userID string) *KafeidoServiceGetUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the kafeido service get user params
func (o *KafeidoServiceGetUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceGetUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
