// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceGetProjectPipelineReader is a Reader for the KafeidoServiceGetProjectPipeline structure.
type KafeidoServiceGetProjectPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceGetProjectPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceGetProjectPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceGetProjectPipelineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceGetProjectPipelineOK creates a KafeidoServiceGetProjectPipelineOK with default headers values
func NewKafeidoServiceGetProjectPipelineOK() *KafeidoServiceGetProjectPipelineOK {
	return &KafeidoServiceGetProjectPipelineOK{}
}

/*
KafeidoServiceGetProjectPipelineOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceGetProjectPipelineOK struct {
	Payload *models.KafeidoGetProjectPipelineResponse
}

// IsSuccess returns true when this kafeido service get project pipeline o k response has a 2xx status code
func (o *KafeidoServiceGetProjectPipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service get project pipeline o k response has a 3xx status code
func (o *KafeidoServiceGetProjectPipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service get project pipeline o k response has a 4xx status code
func (o *KafeidoServiceGetProjectPipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service get project pipeline o k response has a 5xx status code
func (o *KafeidoServiceGetProjectPipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service get project pipeline o k response a status code equal to that given
func (o *KafeidoServiceGetProjectPipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service get project pipeline o k response
func (o *KafeidoServiceGetProjectPipelineOK) Code() int {
	return 200
}

func (o *KafeidoServiceGetProjectPipelineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}][%d] kafeidoServiceGetProjectPipelineOK %s", 200, payload)
}

func (o *KafeidoServiceGetProjectPipelineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}][%d] kafeidoServiceGetProjectPipelineOK %s", 200, payload)
}

func (o *KafeidoServiceGetProjectPipelineOK) GetPayload() *models.KafeidoGetProjectPipelineResponse {
	return o.Payload
}

func (o *KafeidoServiceGetProjectPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoGetProjectPipelineResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoServiceGetProjectPipelineDefault creates a KafeidoServiceGetProjectPipelineDefault with default headers values
func NewKafeidoServiceGetProjectPipelineDefault(code int) *KafeidoServiceGetProjectPipelineDefault {
	return &KafeidoServiceGetProjectPipelineDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceGetProjectPipelineDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceGetProjectPipelineDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service get project pipeline default response has a 2xx status code
func (o *KafeidoServiceGetProjectPipelineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service get project pipeline default response has a 3xx status code
func (o *KafeidoServiceGetProjectPipelineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service get project pipeline default response has a 4xx status code
func (o *KafeidoServiceGetProjectPipelineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service get project pipeline default response has a 5xx status code
func (o *KafeidoServiceGetProjectPipelineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service get project pipeline default response a status code equal to that given
func (o *KafeidoServiceGetProjectPipelineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service get project pipeline default response
func (o *KafeidoServiceGetProjectPipelineDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceGetProjectPipelineDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}][%d] KafeidoService_GetProjectPipeline default %s", o._statusCode, payload)
}

func (o *KafeidoServiceGetProjectPipelineDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}][%d] KafeidoService_GetProjectPipeline default %s", o._statusCode, payload)
}

func (o *KafeidoServiceGetProjectPipelineDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceGetProjectPipelineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
