// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceCreateAPIKeyReader is a Reader for the KafeidoServiceCreateAPIKey structure.
type KafeidoServiceCreateAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceCreateAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceCreateAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceCreateAPIKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceCreateAPIKeyOK creates a KafeidoServiceCreateAPIKeyOK with default headers values
func NewKafeidoServiceCreateAPIKeyOK() *KafeidoServiceCreateAPIKeyOK {
	return &KafeidoServiceCreateAPIKeyOK{}
}

/*
KafeidoServiceCreateAPIKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceCreateAPIKeyOK struct {
	Payload *models.AppkafeidoCreateAPIKeyResponse
}

// IsSuccess returns true when this kafeido service create Api key o k response has a 2xx status code
func (o *KafeidoServiceCreateAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service create Api key o k response has a 3xx status code
func (o *KafeidoServiceCreateAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service create Api key o k response has a 4xx status code
func (o *KafeidoServiceCreateAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service create Api key o k response has a 5xx status code
func (o *KafeidoServiceCreateAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service create Api key o k response a status code equal to that given
func (o *KafeidoServiceCreateAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service create Api key o k response
func (o *KafeidoServiceCreateAPIKeyOK) Code() int {
	return 200
}

func (o *KafeidoServiceCreateAPIKeyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/apikey][%d] kafeidoServiceCreateApiKeyOK %s", 200, payload)
}

func (o *KafeidoServiceCreateAPIKeyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/apikey][%d] kafeidoServiceCreateApiKeyOK %s", 200, payload)
}

func (o *KafeidoServiceCreateAPIKeyOK) GetPayload() *models.AppkafeidoCreateAPIKeyResponse {
	return o.Payload
}

func (o *KafeidoServiceCreateAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppkafeidoCreateAPIKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKafeidoServiceCreateAPIKeyDefault creates a KafeidoServiceCreateAPIKeyDefault with default headers values
func NewKafeidoServiceCreateAPIKeyDefault(code int) *KafeidoServiceCreateAPIKeyDefault {
	return &KafeidoServiceCreateAPIKeyDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceCreateAPIKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceCreateAPIKeyDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service create Api key default response has a 2xx status code
func (o *KafeidoServiceCreateAPIKeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service create Api key default response has a 3xx status code
func (o *KafeidoServiceCreateAPIKeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service create Api key default response has a 4xx status code
func (o *KafeidoServiceCreateAPIKeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service create Api key default response has a 5xx status code
func (o *KafeidoServiceCreateAPIKeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service create Api key default response a status code equal to that given
func (o *KafeidoServiceCreateAPIKeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service create Api key default response
func (o *KafeidoServiceCreateAPIKeyDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceCreateAPIKeyDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/apikey][%d] KafeidoService_CreateApiKey default %s", o._statusCode, payload)
}

func (o *KafeidoServiceCreateAPIKeyDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/apikey][%d] KafeidoService_CreateApiKey default %s", o._statusCode, payload)
}

func (o *KafeidoServiceCreateAPIKeyDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceCreateAPIKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
KafeidoServiceCreateAPIKeyBody kafeido service create API key body
swagger:model KafeidoServiceCreateAPIKeyBody
*/
type KafeidoServiceCreateAPIKeyBody struct {

	// name identifies the external party holding the key - "acme-ci".
	Name string `json:"name,omitempty"`

	// never expires
	NeverExpires bool `json:"neverExpires,omitempty"`

	// role: READ or READWRITE. ADMIN is refused - it has no project tier
	// distinct from READWRITE in this authz model.
	Role *models.KafeidocommonpbAPIKeyRole `json:"role,omitempty"`

	// ttl seconds
	TTLSeconds string `json:"ttlSeconds,omitempty"`
}

// Validate validates this kafeido service create API key body
func (o *KafeidoServiceCreateAPIKeyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KafeidoServiceCreateAPIKeyBody) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(o.Role) { // not required
		return nil
	}

	if o.Role != nil {
		if err := o.Role.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("body" + "." + "role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("body" + "." + "role")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this kafeido service create API key body based on the context it is used
func (o *KafeidoServiceCreateAPIKeyBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KafeidoServiceCreateAPIKeyBody) contextValidateRole(ctx context.Context, formats strfmt.Registry) error {

	if o.Role != nil {

		if swag.IsZero(o.Role) { // not required
			return nil
		}

		if err := o.Role.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("body" + "." + "role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("body" + "." + "role")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *KafeidoServiceCreateAPIKeyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KafeidoServiceCreateAPIKeyBody) UnmarshalBinary(b []byte) error {
	var res KafeidoServiceCreateAPIKeyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
