// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceCreateProjectPipelineReader is a Reader for the KafeidoServiceCreateProjectPipeline structure.
type KafeidoServiceCreateProjectPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceCreateProjectPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceCreateProjectPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceCreateProjectPipelineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceCreateProjectPipelineOK creates a KafeidoServiceCreateProjectPipelineOK with default headers values
func NewKafeidoServiceCreateProjectPipelineOK() *KafeidoServiceCreateProjectPipelineOK {
	return &KafeidoServiceCreateProjectPipelineOK{}
}

/*
KafeidoServiceCreateProjectPipelineOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceCreateProjectPipelineOK struct {
	Payload *models.KafeidoCreateProjectPipelineResponse
}

// IsSuccess returns true when this kafeido service create project pipeline o k response has a 2xx status code
func (o *KafeidoServiceCreateProjectPipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service create project pipeline o k response has a 3xx status code
func (o *KafeidoServiceCreateProjectPipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service create project pipeline o k response has a 4xx status code
func (o *KafeidoServiceCreateProjectPipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service create project pipeline o k response has a 5xx status code
func (o *KafeidoServiceCreateProjectPipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service create project pipeline o k response a status code equal to that given
func (o *KafeidoServiceCreateProjectPipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service create project pipeline o k response
func (o *KafeidoServiceCreateProjectPipelineOK) Code() int {
	return 200
}

func (o *KafeidoServiceCreateProjectPipelineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/pipelines][%d] kafeidoServiceCreateProjectPipelineOK %s", 200, payload)
}

func (o *KafeidoServiceCreateProjectPipelineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/pipelines][%d] kafeidoServiceCreateProjectPipelineOK %s", 200, payload)
}

func (o *KafeidoServiceCreateProjectPipelineOK) GetPayload() *models.KafeidoCreateProjectPipelineResponse {
	return o.Payload
}

func (o *KafeidoServiceCreateProjectPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoCreateProjectPipelineResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoServiceCreateProjectPipelineDefault creates a KafeidoServiceCreateProjectPipelineDefault with default headers values
func NewKafeidoServiceCreateProjectPipelineDefault(code int) *KafeidoServiceCreateProjectPipelineDefault {
	return &KafeidoServiceCreateProjectPipelineDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceCreateProjectPipelineDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceCreateProjectPipelineDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service create project pipeline default response has a 2xx status code
func (o *KafeidoServiceCreateProjectPipelineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service create project pipeline default response has a 3xx status code
func (o *KafeidoServiceCreateProjectPipelineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service create project pipeline default response has a 4xx status code
func (o *KafeidoServiceCreateProjectPipelineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service create project pipeline default response has a 5xx status code
func (o *KafeidoServiceCreateProjectPipelineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service create project pipeline default response a status code equal to that given
func (o *KafeidoServiceCreateProjectPipelineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service create project pipeline default response
func (o *KafeidoServiceCreateProjectPipelineDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceCreateProjectPipelineDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/pipelines][%d] KafeidoService_CreateProjectPipeline default %s", o._statusCode, payload)
}

func (o *KafeidoServiceCreateProjectPipelineDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/projects/{projectId}/pipelines][%d] KafeidoService_CreateProjectPipeline default %s", o._statusCode, payload)
}

func (o *KafeidoServiceCreateProjectPipelineDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceCreateProjectPipelineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
KafeidoServiceCreateProjectPipelineBody kafeido service create project pipeline body
swagger:model KafeidoServiceCreateProjectPipelineBody
*/
type KafeidoServiceCreateProjectPipelineBody struct {

	// desc
	Desc string `json:"desc,omitempty"`

	// kf pipeline workflow
	// Format: byte
	KfPipelineWorkflow strfmt.Base64 `json:"kfPipelineWorkflow,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this kafeido service create project pipeline body
func (o *KafeidoServiceCreateProjectPipelineBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kafeido service create project pipeline body based on context it is used
func (o *KafeidoServiceCreateProjectPipelineBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KafeidoServiceCreateProjectPipelineBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KafeidoServiceCreateProjectPipelineBody) UnmarshalBinary(b []byte) error {
	var res KafeidoServiceCreateProjectPipelineBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
