// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceCreateProjectUploadURLParams creates a new KafeidoServiceCreateProjectUploadURLParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceCreateProjectUploadURLParams() *KafeidoServiceCreateProjectUploadURLParams {
	return &KafeidoServiceCreateProjectUploadURLParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceCreateProjectUploadURLParamsWithTimeout creates a new KafeidoServiceCreateProjectUploadURLParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceCreateProjectUploadURLParamsWithTimeout(timeout time.Duration) *KafeidoServiceCreateProjectUploadURLParams {
	return &KafeidoServiceCreateProjectUploadURLParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceCreateProjectUploadURLParamsWithContext creates a new KafeidoServiceCreateProjectUploadURLParams object
// with the ability to set a context for a request.
func NewKafeidoServiceCreateProjectUploadURLParamsWithContext(ctx context.Context) *KafeidoServiceCreateProjectUploadURLParams {
	return &KafeidoServiceCreateProjectUploadURLParams{
		Context: ctx,
	}
}

// NewKafeidoServiceCreateProjectUploadURLParamsWithHTTPClient creates a new KafeidoServiceCreateProjectUploadURLParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceCreateProjectUploadURLParamsWithHTTPClient(client *http.Client) *KafeidoServiceCreateProjectUploadURLParams {
	return &KafeidoServiceCreateProjectUploadURLParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceCreateProjectUploadURLParams contains all the parameters to send to the API endpoint

	for the kafeido service create project upload Url operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceCreateProjectUploadURLParams struct {

	// Body.
	Body KafeidoServiceCreateProjectUploadURLBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service create project upload Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateProjectUploadURLParams) WithDefaults() *KafeidoServiceCreateProjectUploadURLParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service create project upload Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateProjectUploadURLParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) WithTimeout(timeout time.Duration) *KafeidoServiceCreateProjectUploadURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) WithContext(ctx context.Context) *KafeidoServiceCreateProjectUploadURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) WithHTTPClient(client *http.Client) *KafeidoServiceCreateProjectUploadURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) WithBody(body KafeidoServiceCreateProjectUploadURLBody) *KafeidoServiceCreateProjectUploadURLParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) SetBody(body KafeidoServiceCreateProjectUploadURLBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) WithProjectID(projectID string) *KafeidoServiceCreateProjectUploadURLParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido service create project upload Url params
func (o *KafeidoServiceCreateProjectUploadURLParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceCreateProjectUploadURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
