// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceListProjectsParams creates a new KafeidoServiceListProjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceListProjectsParams() *KafeidoServiceListProjectsParams {
	return &KafeidoServiceListProjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceListProjectsParamsWithTimeout creates a new KafeidoServiceListProjectsParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceListProjectsParamsWithTimeout(timeout time.Duration) *KafeidoServiceListProjectsParams {
	return &KafeidoServiceListProjectsParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceListProjectsParamsWithContext creates a new KafeidoServiceListProjectsParams object
// with the ability to set a context for a request.
func NewKafeidoServiceListProjectsParamsWithContext(ctx context.Context) *KafeidoServiceListProjectsParams {
	return &KafeidoServiceListProjectsParams{
		Context: ctx,
	}
}

// NewKafeidoServiceListProjectsParamsWithHTTPClient creates a new KafeidoServiceListProjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceListProjectsParamsWithHTTPClient(client *http.Client) *KafeidoServiceListProjectsParams {
	return &KafeidoServiceListProjectsParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceListProjectsParams contains all the parameters to send to the API endpoint

	for the kafeido service list projects operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceListProjectsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service list projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceListProjectsParams) WithDefaults() *KafeidoServiceListProjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service list projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceListProjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) WithTimeout(timeout time.Duration) *KafeidoServiceListProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) WithContext(ctx context.Context) *KafeidoServiceListProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) WithHTTPClient(client *http.Client) *KafeidoServiceListProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service list projects params
func (o *KafeidoServiceListProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceListProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
