// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceCancelModelInferenceJobParams creates a new KafeidoServiceCancelModelInferenceJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceCancelModelInferenceJobParams() *KafeidoServiceCancelModelInferenceJobParams {
	return &KafeidoServiceCancelModelInferenceJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceCancelModelInferenceJobParamsWithTimeout creates a new KafeidoServiceCancelModelInferenceJobParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceCancelModelInferenceJobParamsWithTimeout(timeout time.Duration) *KafeidoServiceCancelModelInferenceJobParams {
	return &KafeidoServiceCancelModelInferenceJobParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceCancelModelInferenceJobParamsWithContext creates a new KafeidoServiceCancelModelInferenceJobParams object
// with the ability to set a context for a request.
func NewKafeidoServiceCancelModelInferenceJobParamsWithContext(ctx context.Context) *KafeidoServiceCancelModelInferenceJobParams {
	return &KafeidoServiceCancelModelInferenceJobParams{
		Context: ctx,
	}
}

// NewKafeidoServiceCancelModelInferenceJobParamsWithHTTPClient creates a new KafeidoServiceCancelModelInferenceJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceCancelModelInferenceJobParamsWithHTTPClient(client *http.Client) *KafeidoServiceCancelModelInferenceJobParams {
	return &KafeidoServiceCancelModelInferenceJobParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceCancelModelInferenceJobParams contains all the parameters to send to the API endpoint

	for the kafeido service cancel model inference job operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceCancelModelInferenceJobParams struct {

	// Body.
	Body interface{}

	// ModelInferenceJobID.
	ModelInferenceJobID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service cancel model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCancelModelInferenceJobParams) WithDefaults() *KafeidoServiceCancelModelInferenceJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service cancel model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCancelModelInferenceJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithTimeout(timeout time.Duration) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithContext(ctx context.Context) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithHTTPClient(client *http.Client) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithBody(body interface{}) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetBody(body interface{}) {
	o.Body = body
}

// WithModelInferenceJobID adds the modelInferenceJobID to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithModelInferenceJobID(modelInferenceJobID string) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetModelInferenceJobID(modelInferenceJobID)
	return o
}

// SetModelInferenceJobID adds the modelInferenceJobId to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetModelInferenceJobID(modelInferenceJobID string) {
	o.ModelInferenceJobID = modelInferenceJobID
}

// WithProjectID adds the projectID to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) WithProjectID(projectID string) *KafeidoServiceCancelModelInferenceJobParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido service cancel model inference job params
func (o *KafeidoServiceCancelModelInferenceJobParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceCancelModelInferenceJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param modelInferenceJobId
	if err := r.SetPathParam("modelInferenceJobId", o.ModelInferenceJobID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
