// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceCreateProjectDownloadURLParams creates a new KafeidoServiceCreateProjectDownloadURLParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceCreateProjectDownloadURLParams() *KafeidoServiceCreateProjectDownloadURLParams {
	return &KafeidoServiceCreateProjectDownloadURLParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceCreateProjectDownloadURLParamsWithTimeout creates a new KafeidoServiceCreateProjectDownloadURLParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceCreateProjectDownloadURLParamsWithTimeout(timeout time.Duration) *KafeidoServiceCreateProjectDownloadURLParams {
	return &KafeidoServiceCreateProjectDownloadURLParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceCreateProjectDownloadURLParamsWithContext creates a new KafeidoServiceCreateProjectDownloadURLParams object
// with the ability to set a context for a request.
func NewKafeidoServiceCreateProjectDownloadURLParamsWithContext(ctx context.Context) *KafeidoServiceCreateProjectDownloadURLParams {
	return &KafeidoServiceCreateProjectDownloadURLParams{
		Context: ctx,
	}
}

// NewKafeidoServiceCreateProjectDownloadURLParamsWithHTTPClient creates a new KafeidoServiceCreateProjectDownloadURLParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceCreateProjectDownloadURLParamsWithHTTPClient(client *http.Client) *KafeidoServiceCreateProjectDownloadURLParams {
	return &KafeidoServiceCreateProjectDownloadURLParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceCreateProjectDownloadURLParams contains all the parameters to send to the API endpoint

	for the kafeido service create project download Url operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceCreateProjectDownloadURLParams struct {

	// Body.
	Body KafeidoServiceCreateProjectDownloadURLBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service create project download Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithDefaults() *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service create project download Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithTimeout(timeout time.Duration) *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithContext(ctx context.Context) *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithHTTPClient(client *http.Client) *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithBody(body KafeidoServiceCreateProjectDownloadURLBody) *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetBody(body KafeidoServiceCreateProjectDownloadURLBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) WithProjectID(projectID string) *KafeidoServiceCreateProjectDownloadURLParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido service create project download Url params
func (o *KafeidoServiceCreateProjectDownloadURLParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceCreateProjectDownloadURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
