// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoServiceGetProjectPipelineRunLogsParams creates a new KafeidoServiceGetProjectPipelineRunLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoServiceGetProjectPipelineRunLogsParams() *KafeidoServiceGetProjectPipelineRunLogsParams {
	return &KafeidoServiceGetProjectPipelineRunLogsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoServiceGetProjectPipelineRunLogsParamsWithTimeout creates a new KafeidoServiceGetProjectPipelineRunLogsParams object
// with the ability to set a timeout on a request.
func NewKafeidoServiceGetProjectPipelineRunLogsParamsWithTimeout(timeout time.Duration) *KafeidoServiceGetProjectPipelineRunLogsParams {
	return &KafeidoServiceGetProjectPipelineRunLogsParams{
		timeout: timeout,
	}
}

// NewKafeidoServiceGetProjectPipelineRunLogsParamsWithContext creates a new KafeidoServiceGetProjectPipelineRunLogsParams object
// with the ability to set a context for a request.
func NewKafeidoServiceGetProjectPipelineRunLogsParamsWithContext(ctx context.Context) *KafeidoServiceGetProjectPipelineRunLogsParams {
	return &KafeidoServiceGetProjectPipelineRunLogsParams{
		Context: ctx,
	}
}

// NewKafeidoServiceGetProjectPipelineRunLogsParamsWithHTTPClient creates a new KafeidoServiceGetProjectPipelineRunLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoServiceGetProjectPipelineRunLogsParamsWithHTTPClient(client *http.Client) *KafeidoServiceGetProjectPipelineRunLogsParams {
	return &KafeidoServiceGetProjectPipelineRunLogsParams{
		HTTPClient: client,
	}
}

/*
KafeidoServiceGetProjectPipelineRunLogsParams contains all the parameters to send to the API endpoint

	for the kafeido service get project pipeline run logs operation.

	Typically these are written to a http.Request.
*/
type KafeidoServiceGetProjectPipelineRunLogsParams struct {

	// NamedPipelineID.
	NamedPipelineID string

	// ProjectID.
	ProjectID string

	/* RunID.

	   run_id as returned by RunProjectPipelineResponse.run_id.
	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido service get project pipeline run logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithDefaults() *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido service get project pipeline run logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithTimeout(timeout time.Duration) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithContext(ctx context.Context) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithHTTPClient(client *http.Client) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamedPipelineID adds the namedPipelineID to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithNamedPipelineID(namedPipelineID string) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetNamedPipelineID(namedPipelineID)
	return o
}

// SetNamedPipelineID adds the namedPipelineId to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetNamedPipelineID(namedPipelineID string) {
	o.NamedPipelineID = namedPipelineID
}

// WithProjectID adds the projectID to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithProjectID(projectID string) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithRunID adds the runID to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WithRunID(runID string) *KafeidoServiceGetProjectPipelineRunLogsParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the kafeido service get project pipeline run logs params
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoServiceGetProjectPipelineRunLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namedPipelineId
	if err := r.SetPathParam("namedPipelineId", o.NamedPipelineID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	// path param runId
	if err := r.SetPathParam("runId", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
