// Code generated by go-swagger; DO NOT EDIT.

package kafeido_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoServiceGetProjectPipelineRunLogsReader is a Reader for the KafeidoServiceGetProjectPipelineRunLogs structure.
type KafeidoServiceGetProjectPipelineRunLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoServiceGetProjectPipelineRunLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoServiceGetProjectPipelineRunLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoServiceGetProjectPipelineRunLogsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoServiceGetProjectPipelineRunLogsOK creates a KafeidoServiceGetProjectPipelineRunLogsOK with default headers values
func NewKafeidoServiceGetProjectPipelineRunLogsOK() *KafeidoServiceGetProjectPipelineRunLogsOK {
	return &KafeidoServiceGetProjectPipelineRunLogsOK{}
}

/*
KafeidoServiceGetProjectPipelineRunLogsOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoServiceGetProjectPipelineRunLogsOK struct {
	Payload *models.KafeidoGetProjectPipelineRunLogsResponse
}

// IsSuccess returns true when this kafeido service get project pipeline run logs o k response has a 2xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido service get project pipeline run logs o k response has a 3xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido service get project pipeline run logs o k response has a 4xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido service get project pipeline run logs o k response has a 5xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido service get project pipeline run logs o k response a status code equal to that given
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido service get project pipeline run logs o k response
func (o *KafeidoServiceGetProjectPipelineRunLogsOK) Code() int {
	return 200
}

func (o *KafeidoServiceGetProjectPipelineRunLogsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}/runs/{runId}/logs][%d] kafeidoServiceGetProjectPipelineRunLogsOK %s", 200, payload)
}

func (o *KafeidoServiceGetProjectPipelineRunLogsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}/runs/{runId}/logs][%d] kafeidoServiceGetProjectPipelineRunLogsOK %s", 200, payload)
}

func (o *KafeidoServiceGetProjectPipelineRunLogsOK) GetPayload() *models.KafeidoGetProjectPipelineRunLogsResponse {
	return o.Payload
}

func (o *KafeidoServiceGetProjectPipelineRunLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoGetProjectPipelineRunLogsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKafeidoServiceGetProjectPipelineRunLogsDefault creates a KafeidoServiceGetProjectPipelineRunLogsDefault with default headers values
func NewKafeidoServiceGetProjectPipelineRunLogsDefault(code int) *KafeidoServiceGetProjectPipelineRunLogsDefault {
	return &KafeidoServiceGetProjectPipelineRunLogsDefault{
		_statusCode: code,
	}
}

/*
KafeidoServiceGetProjectPipelineRunLogsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoServiceGetProjectPipelineRunLogsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido service get project pipeline run logs default response has a 2xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido service get project pipeline run logs default response has a 3xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido service get project pipeline run logs default response has a 4xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido service get project pipeline run logs default response has a 5xx status code
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido service get project pipeline run logs default response a status code equal to that given
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido service get project pipeline run logs default response
func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}/runs/{runId}/logs][%d] KafeidoService_GetProjectPipelineRunLogs default %s", o._statusCode, payload)
}

func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/projects/{projectId}/pipelines/{namedPipelineId}/runs/{runId}/logs][%d] KafeidoService_GetProjectPipelineRunLogs default %s", o._statusCode, payload)
}

func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoServiceGetProjectPipelineRunLogsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
