// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppkafeidoCreateAPIKeyResponse appkafeido create Api key response
//
// swagger:model appkafeidoCreateApiKeyResponse
type AppkafeidoCreateAPIKeyResponse struct {

	// key
	Key *AppkafeidoAPIKeyInfo `json:"key,omitempty"`

	// The credential, returned exactly once and never recoverable.
	Token string `json:"token,omitempty"`
}

// Validate validates this appkafeido create Api key response
func (m *AppkafeidoCreateAPIKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoCreateAPIKeyResponse) validateKey(formats strfmt.Registry) error {
	if swag.IsZero(m.Key) { // not required
		return nil
	}

	if m.Key != nil {
		if err := m.Key.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("key")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("key")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this appkafeido create Api key response based on the context it is used
func (m *AppkafeidoCreateAPIKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoCreateAPIKeyResponse) contextValidateKey(ctx context.Context, formats strfmt.Registry) error {

	if m.Key != nil {

		if swag.IsZero(m.Key) { // not required
			return nil
		}

		if err := m.Key.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("key")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("key")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppkafeidoCreateAPIKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppkafeidoCreateAPIKeyResponse) UnmarshalBinary(b []byte) error {
	var res AppkafeidoCreateAPIKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
