// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppkafeidoCreateDataSourceResponse appkafeido create data source response
//
// swagger:model appkafeidoCreateDataSourceResponse
type AppkafeidoCreateDataSourceResponse struct {

	// data source Id
	DataSourceID string `json:"dataSourceId,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`
}

// Validate validates this appkafeido create data source response
func (m *AppkafeidoCreateDataSourceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this appkafeido create data source response based on context it is used
func (m *AppkafeidoCreateDataSourceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppkafeidoCreateDataSourceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppkafeidoCreateDataSourceResponse) UnmarshalBinary(b []byte) error {
	var res AppkafeidoCreateDataSourceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
