// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppkafeidoDataSink appkafeido data sink
//
// swagger:model appkafeidoDataSink
type AppkafeidoDataSink struct {

	// object store data sink
	ObjectStoreDataSink *AppkafeidoObjectStoreDataSink `json:"objectStoreDataSink,omitempty"`

	// redis data sink
	RedisDataSink *AppkafeidoRedisStreamSink `json:"redisDataSink,omitempty"`
}

// Validate validates this appkafeido data sink
func (m *AppkafeidoDataSink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObjectStoreDataSink(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRedisDataSink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoDataSink) validateObjectStoreDataSink(formats strfmt.Registry) error {
	if swag.IsZero(m.ObjectStoreDataSink) { // not required
		return nil
	}

	if m.ObjectStoreDataSink != nil {
		if err := m.ObjectStoreDataSink.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("objectStoreDataSink")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("objectStoreDataSink")
			}
			return err
		}
	}

	return nil
}

func (m *AppkafeidoDataSink) validateRedisDataSink(formats strfmt.Registry) error {
	if swag.IsZero(m.RedisDataSink) { // not required
		return nil
	}

	if m.RedisDataSink != nil {
		if err := m.RedisDataSink.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redisDataSink")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("redisDataSink")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this appkafeido data sink based on the context it is used
func (m *AppkafeidoDataSink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateObjectStoreDataSink(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRedisDataSink(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoDataSink) contextValidateObjectStoreDataSink(ctx context.Context, formats strfmt.Registry) error {

	if m.ObjectStoreDataSink != nil {

		if swag.IsZero(m.ObjectStoreDataSink) { // not required
			return nil
		}

		if err := m.ObjectStoreDataSink.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("objectStoreDataSink")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("objectStoreDataSink")
			}
			return err
		}
	}

	return nil
}

func (m *AppkafeidoDataSink) contextValidateRedisDataSink(ctx context.Context, formats strfmt.Registry) error {

	if m.RedisDataSink != nil {

		if swag.IsZero(m.RedisDataSink) { // not required
			return nil
		}

		if err := m.RedisDataSink.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redisDataSink")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("redisDataSink")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppkafeidoDataSink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppkafeidoDataSink) UnmarshalBinary(b []byte) error {
	var res AppkafeidoDataSink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
