// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppkafeidoAPIKeyInfo ApiKeyInfo is a key as an operator sees it. No secret, no hash - there is no
// shape of this message that can authenticate anything.
//
// swagger:model appkafeidoApiKeyInfo
type AppkafeidoAPIKeyInfo struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// expires at
	ExpiresAt string `json:"expiresAt,omitempty"`

	// key Id
	KeyID string `json:"keyId,omitempty"`

	// last used at
	LastUsedAt string `json:"lastUsedAt,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`

	// revoked at
	RevokedAt string `json:"revokedAt,omitempty"`

	// role
	Role *KafeidocommonpbAPIKeyRole `json:"role,omitempty"`
}

// Validate validates this appkafeido Api key info
func (m *AppkafeidoAPIKeyInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoAPIKeyInfo) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(m.Role) { // not required
		return nil
	}

	if m.Role != nil {
		if err := m.Role.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("role")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this appkafeido Api key info based on the context it is used
func (m *AppkafeidoAPIKeyInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppkafeidoAPIKeyInfo) contextValidateRole(ctx context.Context, formats strfmt.Registry) error {

	if m.Role != nil {

		if swag.IsZero(m.Role) { // not required
			return nil
		}

		if err := m.Role.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("role")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppkafeidoAPIKeyInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppkafeidoAPIKeyInfo) UnmarshalBinary(b []byte) error {
	var res AppkafeidoAPIKeyInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
