// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ComptaskworkerObjectStoreInfo comptaskworker object store info
//
// swagger:model comptaskworkerObjectStoreInfo
type ComptaskworkerObjectStoreInfo struct {

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// use Tls
	UseTLS bool `json:"useTls,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`

	// user secret
	UserSecret string `json:"userSecret,omitempty"`
}

// Validate validates this comptaskworker object store info
func (m *ComptaskworkerObjectStoreInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this comptaskworker object store info based on context it is used
func (m *ComptaskworkerObjectStoreInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComptaskworkerObjectStoreInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComptaskworkerObjectStoreInfo) UnmarshalBinary(b []byte) error {
	var res ComptaskworkerObjectStoreInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
