// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatastreamVideoDataSource datastream video data source
//
// swagger:model datastreamVideoDataSource
type DatastreamVideoDataSource struct {

	// bucket name
	BucketName string `json:"bucketName,omitempty"`

	// frames per second
	FramesPerSecond float32 `json:"framesPerSecond,omitempty"`

	// repeated times
	RepeatedTimes int32 `json:"repeatedTimes,omitempty"`

	// storage info
	StorageInfo *DatastreamStorageInfo `json:"storageInfo,omitempty"`

	// video path
	VideoPath string `json:"videoPath,omitempty"`
}

// Validate validates this datastream video data source
func (m *DatastreamVideoDataSource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStorageInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DatastreamVideoDataSource) validateStorageInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.StorageInfo) { // not required
		return nil
	}

	if m.StorageInfo != nil {
		if err := m.StorageInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storageInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("storageInfo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this datastream video data source based on the context it is used
func (m *DatastreamVideoDataSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStorageInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DatastreamVideoDataSource) contextValidateStorageInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.StorageInfo != nil {

		if swag.IsZero(m.StorageInfo) { // not required
			return nil
		}

		if err := m.StorageInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storageInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("storageInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DatastreamVideoDataSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatastreamVideoDataSource) UnmarshalBinary(b []byte) error {
	var res DatastreamVideoDataSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
