// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KafeidoListModelInferenceResponse kafeido list model inference response
//
// swagger:model kafeidoListModelInferenceResponse
type KafeidoListModelInferenceResponse struct {

	// model inference Id
	ModelInferenceID []string `json:"modelInferenceId"`
}

// Validate validates this kafeido list model inference response
func (m *KafeidoListModelInferenceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kafeido list model inference response based on context it is used
func (m *KafeidoListModelInferenceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoListModelInferenceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoListModelInferenceResponse) UnmarshalBinary(b []byte) error {
	var res KafeidoListModelInferenceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
