// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KafeidoDeleteProjectObjectResponse kafeido delete project object response
//
// swagger:model kafeidoDeleteProjectObjectResponse
type KafeidoDeleteProjectObjectResponse struct {

	// bucket name
	BucketName string `json:"bucketName,omitempty"`

	// object name
	ObjectName string `json:"objectName,omitempty"`
}

// Validate validates this kafeido delete project object response
func (m *KafeidoDeleteProjectObjectResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kafeido delete project object response based on context it is used
func (m *KafeidoDeleteProjectObjectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoDeleteProjectObjectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoDeleteProjectObjectResponse) UnmarshalBinary(b []byte) error {
	var res KafeidoDeleteProjectObjectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
