// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KafeidoCreateProjectUploadURLResponse kafeido create project upload Url response
//
// swagger:model kafeidoCreateProjectUploadUrlResponse
type KafeidoCreateProjectUploadURLResponse struct {

	// bucket name
	BucketName string `json:"bucketName,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expiresAt,omitempty"`

	// Largest upload this url can carry in one PUT. A caller that ignores it
	// gets a failed upload, never a truncated object.
	MaxBytes string `json:"maxBytes,omitempty"`

	// object name
	ObjectName string `json:"objectName,omitempty"`

	// Presigned PUT url. SINGLE PUT ONLY - the general client SDKs do not
	// support multipart with presigned URLs, so a file larger than
	// max_bytes must not be split across this url.
	UploadURL string `json:"uploadUrl,omitempty"`
}

// Validate validates this kafeido create project upload Url response
func (m *KafeidoCreateProjectUploadURLResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KafeidoCreateProjectUploadURLResponse) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expiresAt", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kafeido create project upload Url response based on context it is used
func (m *KafeidoCreateProjectUploadURLResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoCreateProjectUploadURLResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoCreateProjectUploadURLResponse) UnmarshalBinary(b []byte) error {
	var res KafeidoCreateProjectUploadURLResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
