// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KafeidoPredictAudioResponseBody kafeido predict audio response body
//
// swagger:model kafeidoPredictAudioResponseBody
type KafeidoPredictAudioResponseBody struct {

	// key
	Key string `json:"key,omitempty"`

	// prediction
	Prediction *KafeidoResponseInJSON `json:"prediction,omitempty"`
}

// Validate validates this kafeido predict audio response body
func (m *KafeidoPredictAudioResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrediction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KafeidoPredictAudioResponseBody) validatePrediction(formats strfmt.Registry) error {
	if swag.IsZero(m.Prediction) { // not required
		return nil
	}

	if m.Prediction != nil {
		if err := m.Prediction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("prediction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("prediction")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this kafeido predict audio response body based on the context it is used
func (m *KafeidoPredictAudioResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrediction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KafeidoPredictAudioResponseBody) contextValidatePrediction(ctx context.Context, formats strfmt.Registry) error {

	if m.Prediction != nil {

		if swag.IsZero(m.Prediction) { // not required
			return nil
		}

		if err := m.Prediction.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("prediction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("prediction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoPredictAudioResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoPredictAudioResponseBody) UnmarshalBinary(b []byte) error {
	var res KafeidoPredictAudioResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
