// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KafeidoListProjectsResponse kafeido list projects response
//
// swagger:model kafeidoListProjectsResponse
type KafeidoListProjectsResponse struct {

	// project ids
	ProjectIds []string `json:"projectIds"`
}

// Validate validates this kafeido list projects response
func (m *KafeidoListProjectsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kafeido list projects response based on context it is used
func (m *KafeidoListProjectsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoListProjectsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoListProjectsResponse) UnmarshalBinary(b []byte) error {
	var res KafeidoListProjectsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
