// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KafeidoRunLogSegment RunLogSegment is one pod's archived log output.
//
// Segments rather than one concatenated blob: the logs are fetched per pod
// either way, and returning them separately makes per-node selection a
// client-side filter instead of a second RPC. Concatenating is a one-line join
// in the UI (grandturks#823).
//
// swagger:model kafeidoRunLogSegment
type KafeidoRunLogSegment struct {

	// content
	// Format: byte
	Content strfmt.Base64 `json:"content,omitempty"`

	// From KFP's TaskDetails[].PodName - not derived from anything.
	PodName string `json:"podName,omitempty"`

	// TaskDetail.DisplayName, so the UI can label the segment.
	TaskName string `json:"taskName,omitempty"`

	// The segment hit the per-segment byte cap and was cut short. The RPC
	// truncates rather than streaming an unbounded body into one message.
	Truncated bool `json:"truncated,omitempty"`
}

// Validate validates this kafeido run log segment
func (m *KafeidoRunLogSegment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kafeido run log segment based on context it is used
func (m *KafeidoRunLogSegment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KafeidoRunLogSegment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KafeidoRunLogSegment) UnmarshalBinary(b []byte) error {
	var res KafeidoRunLogSegment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
