// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// StreamingInfoProtocol streaming info protocol
//
// swagger:model StreamingInfoProtocol
type StreamingInfoProtocol string

func NewStreamingInfoProtocol(value StreamingInfoProtocol) *StreamingInfoProtocol {
	return &value
}

// Pointer returns a pointer to a freshly-allocated StreamingInfoProtocol.
func (m StreamingInfoProtocol) Pointer() *StreamingInfoProtocol {
	return &m
}

const (

	// StreamingInfoProtocolSTREAMINGPROTOCOLNONE captures enum value "STREAMING_PROTOCOL_NONE"
	StreamingInfoProtocolSTREAMINGPROTOCOLNONE StreamingInfoProtocol = "STREAMING_PROTOCOL_NONE"

	// StreamingInfoProtocolSTREAMINGPROTOCOLRTSP captures enum value "STREAMING_PROTOCOL_RTSP"
	StreamingInfoProtocolSTREAMINGPROTOCOLRTSP StreamingInfoProtocol = "STREAMING_PROTOCOL_RTSP"

	// StreamingInfoProtocolSTREAMINGPROTOCOLRTMP captures enum value "STREAMING_PROTOCOL_RTMP"
	StreamingInfoProtocolSTREAMINGPROTOCOLRTMP StreamingInfoProtocol = "STREAMING_PROTOCOL_RTMP"

	// StreamingInfoProtocolSTREAMINGPROTOCOLRTSPS captures enum value "STREAMING_PROTOCOL_RTSPS"
	StreamingInfoProtocolSTREAMINGPROTOCOLRTSPS StreamingInfoProtocol = "STREAMING_PROTOCOL_RTSPS"

	// StreamingInfoProtocolSTREAMINGPROTOCOLRTMPS captures enum value "STREAMING_PROTOCOL_RTMPS"
	StreamingInfoProtocolSTREAMINGPROTOCOLRTMPS StreamingInfoProtocol = "STREAMING_PROTOCOL_RTMPS"
)

// for schema
var streamingInfoProtocolEnum []interface{}

func init() {
	var res []StreamingInfoProtocol
	if err := json.Unmarshal([]byte(`["STREAMING_PROTOCOL_NONE","STREAMING_PROTOCOL_RTSP","STREAMING_PROTOCOL_RTMP","STREAMING_PROTOCOL_RTSPS","STREAMING_PROTOCOL_RTMPS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		streamingInfoProtocolEnum = append(streamingInfoProtocolEnum, v)
	}
}

func (m StreamingInfoProtocol) validateStreamingInfoProtocolEnum(path, location string, value StreamingInfoProtocol) error {
	if err := validate.EnumCase(path, location, value, streamingInfoProtocolEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this streaming info protocol
func (m StreamingInfoProtocol) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateStreamingInfoProtocolEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this streaming info protocol based on context it is used
func (m StreamingInfoProtocol) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
