{
 "title": "Grandturks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ProcTime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC Error code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "count by (httpcode, method) (rate(rpc_server_requests_request_code_total{httpcode!=\"0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50/P95 Duration(ms) ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 1, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (method, le) (rate(rpc_server_requests_request_duration_ms_bucket[1m])))",
     "legendFormat": "p50-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (method, le) (rate(rpc_server_requests_request_duration_ms_bucket[1m])))",
     "legendFormat": "p95-{{method}}"
    }
   ]
  },
  {
   "title": "Mean Proctime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (method) (rate(rpc_server_requests_request_duration_ms_sum[5m])/rate(rpc_server_requests_request_duration_ms_count[5m]))",
     "legendFormat": "mean-{{method}}"
    }
   ]
  }
 ]
}