// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoCreateDataSourceReader is a Reader for the KafeidoCreateDataSource structure.
type KafeidoCreateDataSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoCreateDataSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoCreateDataSourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoCreateDataSourceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoCreateDataSourceOK creates a KafeidoCreateDataSourceOK with default headers values
func NewKafeidoCreateDataSourceOK() *KafeidoCreateDataSourceOK {
	return &KafeidoCreateDataSourceOK{}
}

/*
KafeidoCreateDataSourceOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoCreateDataSourceOK struct {
	Payload *models.AppkafeidoCreateDataSourceResponse
}

// IsSuccess returns true when this kafeido create data source o k response has a 2xx status code
func (o *KafeidoCreateDataSourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido create data source o k response has a 3xx status code
func (o *KafeidoCreateDataSourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido create data source o k response has a 4xx status code
func (o *KafeidoCreateDataSourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido create data source o k response has a 5xx status code
func (o *KafeidoCreateDataSourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido create data source o k response a status code equal to that given
func (o *KafeidoCreateDataSourceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido create data source o k response
func (o *KafeidoCreateDataSourceOK) Code() int {
	return 200
}

func (o *KafeidoCreateDataSourceOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/datasource][%d] kafeidoCreateDataSourceOK  %+v", 200, o.Payload)
}

func (o *KafeidoCreateDataSourceOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/datasource][%d] kafeidoCreateDataSourceOK  %+v", 200, o.Payload)
}

func (o *KafeidoCreateDataSourceOK) GetPayload() *models.AppkafeidoCreateDataSourceResponse {
	return o.Payload
}

func (o *KafeidoCreateDataSourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppkafeidoCreateDataSourceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoCreateDataSourceDefault creates a KafeidoCreateDataSourceDefault with default headers values
func NewKafeidoCreateDataSourceDefault(code int) *KafeidoCreateDataSourceDefault {
	return &KafeidoCreateDataSourceDefault{
		_statusCode: code,
	}
}

/*
KafeidoCreateDataSourceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoCreateDataSourceDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido create data source default response has a 2xx status code
func (o *KafeidoCreateDataSourceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido create data source default response has a 3xx status code
func (o *KafeidoCreateDataSourceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido create data source default response has a 4xx status code
func (o *KafeidoCreateDataSourceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido create data source default response has a 5xx status code
func (o *KafeidoCreateDataSourceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido create data source default response a status code equal to that given
func (o *KafeidoCreateDataSourceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido create data source default response
func (o *KafeidoCreateDataSourceDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoCreateDataSourceDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/datasource][%d] kafeido_CreateDataSource default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCreateDataSourceDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/datasource][%d] kafeido_CreateDataSource default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCreateDataSourceDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoCreateDataSourceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
KafeidoCreateDataSourceBody kafeido create data source body
swagger:model KafeidoCreateDataSourceBody
*/
type KafeidoCreateDataSourceBody struct {

	// data source info
	DataSourceInfo *models.KafeidoDataSourceInfo `json:"dataSourceInfo,omitempty"`
}

// Validate validates this kafeido create data source body
func (o *KafeidoCreateDataSourceBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDataSourceInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KafeidoCreateDataSourceBody) validateDataSourceInfo(formats strfmt.Registry) error {
	if swag.IsZero(o.DataSourceInfo) { // not required
		return nil
	}

	if o.DataSourceInfo != nil {
		if err := o.DataSourceInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "dataSourceInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "dataSourceInfo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this kafeido create data source body based on the context it is used
func (o *KafeidoCreateDataSourceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDataSourceInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KafeidoCreateDataSourceBody) contextValidateDataSourceInfo(ctx context.Context, formats strfmt.Registry) error {

	if o.DataSourceInfo != nil {

		if swag.IsZero(o.DataSourceInfo) { // not required
			return nil
		}

		if err := o.DataSourceInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "dataSourceInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "dataSourceInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *KafeidoCreateDataSourceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KafeidoCreateDataSourceBody) UnmarshalBinary(b []byte) error {
	var res KafeidoCreateDataSourceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
