// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoCreateProjectPipelineParams creates a new KafeidoCreateProjectPipelineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoCreateProjectPipelineParams() *KafeidoCreateProjectPipelineParams {
	return &KafeidoCreateProjectPipelineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoCreateProjectPipelineParamsWithTimeout creates a new KafeidoCreateProjectPipelineParams object
// with the ability to set a timeout on a request.
func NewKafeidoCreateProjectPipelineParamsWithTimeout(timeout time.Duration) *KafeidoCreateProjectPipelineParams {
	return &KafeidoCreateProjectPipelineParams{
		timeout: timeout,
	}
}

// NewKafeidoCreateProjectPipelineParamsWithContext creates a new KafeidoCreateProjectPipelineParams object
// with the ability to set a context for a request.
func NewKafeidoCreateProjectPipelineParamsWithContext(ctx context.Context) *KafeidoCreateProjectPipelineParams {
	return &KafeidoCreateProjectPipelineParams{
		Context: ctx,
	}
}

// NewKafeidoCreateProjectPipelineParamsWithHTTPClient creates a new KafeidoCreateProjectPipelineParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoCreateProjectPipelineParamsWithHTTPClient(client *http.Client) *KafeidoCreateProjectPipelineParams {
	return &KafeidoCreateProjectPipelineParams{
		HTTPClient: client,
	}
}

/*
KafeidoCreateProjectPipelineParams contains all the parameters to send to the API endpoint

	for the kafeido create project pipeline operation.

	Typically these are written to a http.Request.
*/
type KafeidoCreateProjectPipelineParams struct {

	// Body.
	Body KafeidoCreateProjectPipelineBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido create project pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCreateProjectPipelineParams) WithDefaults() *KafeidoCreateProjectPipelineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido create project pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCreateProjectPipelineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) WithTimeout(timeout time.Duration) *KafeidoCreateProjectPipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) WithContext(ctx context.Context) *KafeidoCreateProjectPipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) WithHTTPClient(client *http.Client) *KafeidoCreateProjectPipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) WithBody(body KafeidoCreateProjectPipelineBody) *KafeidoCreateProjectPipelineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) SetBody(body KafeidoCreateProjectPipelineBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) WithProjectID(projectID string) *KafeidoCreateProjectPipelineParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido create project pipeline params
func (o *KafeidoCreateProjectPipelineParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoCreateProjectPipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
