// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoListModelInferenceJobReader is a Reader for the KafeidoListModelInferenceJob structure.
type KafeidoListModelInferenceJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoListModelInferenceJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoListModelInferenceJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoListModelInferenceJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoListModelInferenceJobOK creates a KafeidoListModelInferenceJobOK with default headers values
func NewKafeidoListModelInferenceJobOK() *KafeidoListModelInferenceJobOK {
	return &KafeidoListModelInferenceJobOK{}
}

/*
KafeidoListModelInferenceJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoListModelInferenceJobOK struct {
	Payload *models.KafeidoListModelInferenceJobResponse
}

// IsSuccess returns true when this kafeido list model inference job o k response has a 2xx status code
func (o *KafeidoListModelInferenceJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido list model inference job o k response has a 3xx status code
func (o *KafeidoListModelInferenceJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido list model inference job o k response has a 4xx status code
func (o *KafeidoListModelInferenceJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido list model inference job o k response has a 5xx status code
func (o *KafeidoListModelInferenceJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido list model inference job o k response a status code equal to that given
func (o *KafeidoListModelInferenceJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido list model inference job o k response
func (o *KafeidoListModelInferenceJobOK) Code() int {
	return 200
}

func (o *KafeidoListModelInferenceJobOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeidoListModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoListModelInferenceJobOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeidoListModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoListModelInferenceJobOK) GetPayload() *models.KafeidoListModelInferenceJobResponse {
	return o.Payload
}

func (o *KafeidoListModelInferenceJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoListModelInferenceJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoListModelInferenceJobDefault creates a KafeidoListModelInferenceJobDefault with default headers values
func NewKafeidoListModelInferenceJobDefault(code int) *KafeidoListModelInferenceJobDefault {
	return &KafeidoListModelInferenceJobDefault{
		_statusCode: code,
	}
}

/*
KafeidoListModelInferenceJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoListModelInferenceJobDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido list model inference job default response has a 2xx status code
func (o *KafeidoListModelInferenceJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido list model inference job default response has a 3xx status code
func (o *KafeidoListModelInferenceJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido list model inference job default response has a 4xx status code
func (o *KafeidoListModelInferenceJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido list model inference job default response has a 5xx status code
func (o *KafeidoListModelInferenceJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido list model inference job default response a status code equal to that given
func (o *KafeidoListModelInferenceJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido list model inference job default response
func (o *KafeidoListModelInferenceJobDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoListModelInferenceJobDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeido_ListModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoListModelInferenceJobDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job][%d] kafeido_ListModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoListModelInferenceJobDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoListModelInferenceJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
