// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoListModelInferenceReader is a Reader for the KafeidoListModelInference structure.
type KafeidoListModelInferenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoListModelInferenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoListModelInferenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoListModelInferenceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoListModelInferenceOK creates a KafeidoListModelInferenceOK with default headers values
func NewKafeidoListModelInferenceOK() *KafeidoListModelInferenceOK {
	return &KafeidoListModelInferenceOK{}
}

/*
KafeidoListModelInferenceOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoListModelInferenceOK struct {
	Payload *models.KafeidoListModelInferenceResponse
}

// IsSuccess returns true when this kafeido list model inference o k response has a 2xx status code
func (o *KafeidoListModelInferenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido list model inference o k response has a 3xx status code
func (o *KafeidoListModelInferenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido list model inference o k response has a 4xx status code
func (o *KafeidoListModelInferenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido list model inference o k response has a 5xx status code
func (o *KafeidoListModelInferenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido list model inference o k response a status code equal to that given
func (o *KafeidoListModelInferenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido list model inference o k response
func (o *KafeidoListModelInferenceOK) Code() int {
	return 200
}

func (o *KafeidoListModelInferenceOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/inference][%d] kafeidoListModelInferenceOK  %+v", 200, o.Payload)
}

func (o *KafeidoListModelInferenceOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/inference][%d] kafeidoListModelInferenceOK  %+v", 200, o.Payload)
}

func (o *KafeidoListModelInferenceOK) GetPayload() *models.KafeidoListModelInferenceResponse {
	return o.Payload
}

func (o *KafeidoListModelInferenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoListModelInferenceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoListModelInferenceDefault creates a KafeidoListModelInferenceDefault with default headers values
func NewKafeidoListModelInferenceDefault(code int) *KafeidoListModelInferenceDefault {
	return &KafeidoListModelInferenceDefault{
		_statusCode: code,
	}
}

/*
KafeidoListModelInferenceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoListModelInferenceDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido list model inference default response has a 2xx status code
func (o *KafeidoListModelInferenceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido list model inference default response has a 3xx status code
func (o *KafeidoListModelInferenceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido list model inference default response has a 4xx status code
func (o *KafeidoListModelInferenceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido list model inference default response has a 5xx status code
func (o *KafeidoListModelInferenceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido list model inference default response a status code equal to that given
func (o *KafeidoListModelInferenceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido list model inference default response
func (o *KafeidoListModelInferenceDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoListModelInferenceDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/inference][%d] kafeido_ListModelInference default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoListModelInferenceDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/inference][%d] kafeido_ListModelInference default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoListModelInferenceDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoListModelInferenceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
