// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoGetModelInferenceJobReader is a Reader for the KafeidoGetModelInferenceJob structure.
type KafeidoGetModelInferenceJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoGetModelInferenceJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoGetModelInferenceJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoGetModelInferenceJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoGetModelInferenceJobOK creates a KafeidoGetModelInferenceJobOK with default headers values
func NewKafeidoGetModelInferenceJobOK() *KafeidoGetModelInferenceJobOK {
	return &KafeidoGetModelInferenceJobOK{}
}

/*
KafeidoGetModelInferenceJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoGetModelInferenceJobOK struct {
	Payload *models.KafeidoGetModelInferenceJobResponse
}

// IsSuccess returns true when this kafeido get model inference job o k response has a 2xx status code
func (o *KafeidoGetModelInferenceJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido get model inference job o k response has a 3xx status code
func (o *KafeidoGetModelInferenceJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido get model inference job o k response has a 4xx status code
func (o *KafeidoGetModelInferenceJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido get model inference job o k response has a 5xx status code
func (o *KafeidoGetModelInferenceJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido get model inference job o k response a status code equal to that given
func (o *KafeidoGetModelInferenceJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido get model inference job o k response
func (o *KafeidoGetModelInferenceJobOK) Code() int {
	return 200
}

func (o *KafeidoGetModelInferenceJobOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeidoGetModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoGetModelInferenceJobOK) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeidoGetModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoGetModelInferenceJobOK) GetPayload() *models.KafeidoGetModelInferenceJobResponse {
	return o.Payload
}

func (o *KafeidoGetModelInferenceJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoGetModelInferenceJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoGetModelInferenceJobDefault creates a KafeidoGetModelInferenceJobDefault with default headers values
func NewKafeidoGetModelInferenceJobDefault(code int) *KafeidoGetModelInferenceJobDefault {
	return &KafeidoGetModelInferenceJobDefault{
		_statusCode: code,
	}
}

/*
KafeidoGetModelInferenceJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoGetModelInferenceJobDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido get model inference job default response has a 2xx status code
func (o *KafeidoGetModelInferenceJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido get model inference job default response has a 3xx status code
func (o *KafeidoGetModelInferenceJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido get model inference job default response has a 4xx status code
func (o *KafeidoGetModelInferenceJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido get model inference job default response has a 5xx status code
func (o *KafeidoGetModelInferenceJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido get model inference job default response a status code equal to that given
func (o *KafeidoGetModelInferenceJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido get model inference job default response
func (o *KafeidoGetModelInferenceJobDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoGetModelInferenceJobDefault) Error() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeido_GetModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoGetModelInferenceJobDefault) String() string {
	return fmt.Sprintf("[GET /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeido_GetModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoGetModelInferenceJobDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoGetModelInferenceJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
