// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoDeleteModelInferenceJobReader is a Reader for the KafeidoDeleteModelInferenceJob structure.
type KafeidoDeleteModelInferenceJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoDeleteModelInferenceJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoDeleteModelInferenceJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoDeleteModelInferenceJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoDeleteModelInferenceJobOK creates a KafeidoDeleteModelInferenceJobOK with default headers values
func NewKafeidoDeleteModelInferenceJobOK() *KafeidoDeleteModelInferenceJobOK {
	return &KafeidoDeleteModelInferenceJobOK{}
}

/*
KafeidoDeleteModelInferenceJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoDeleteModelInferenceJobOK struct {
	Payload models.KafeidoDeleteModelInferenceJobResponse
}

// IsSuccess returns true when this kafeido delete model inference job o k response has a 2xx status code
func (o *KafeidoDeleteModelInferenceJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido delete model inference job o k response has a 3xx status code
func (o *KafeidoDeleteModelInferenceJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido delete model inference job o k response has a 4xx status code
func (o *KafeidoDeleteModelInferenceJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido delete model inference job o k response has a 5xx status code
func (o *KafeidoDeleteModelInferenceJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido delete model inference job o k response a status code equal to that given
func (o *KafeidoDeleteModelInferenceJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido delete model inference job o k response
func (o *KafeidoDeleteModelInferenceJobOK) Code() int {
	return 200
}

func (o *KafeidoDeleteModelInferenceJobOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeidoDeleteModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoDeleteModelInferenceJobOK) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeidoDeleteModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoDeleteModelInferenceJobOK) GetPayload() models.KafeidoDeleteModelInferenceJobResponse {
	return o.Payload
}

func (o *KafeidoDeleteModelInferenceJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoDeleteModelInferenceJobDefault creates a KafeidoDeleteModelInferenceJobDefault with default headers values
func NewKafeidoDeleteModelInferenceJobDefault(code int) *KafeidoDeleteModelInferenceJobDefault {
	return &KafeidoDeleteModelInferenceJobDefault{
		_statusCode: code,
	}
}

/*
KafeidoDeleteModelInferenceJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoDeleteModelInferenceJobDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido delete model inference job default response has a 2xx status code
func (o *KafeidoDeleteModelInferenceJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido delete model inference job default response has a 3xx status code
func (o *KafeidoDeleteModelInferenceJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido delete model inference job default response has a 4xx status code
func (o *KafeidoDeleteModelInferenceJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido delete model inference job default response has a 5xx status code
func (o *KafeidoDeleteModelInferenceJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido delete model inference job default response a status code equal to that given
func (o *KafeidoDeleteModelInferenceJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido delete model inference job default response
func (o *KafeidoDeleteModelInferenceJobDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoDeleteModelInferenceJobDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeido_DeleteModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoDeleteModelInferenceJobDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/projects/{projectId}/job/{modelInferenceJobId}][%d] kafeido_DeleteModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoDeleteModelInferenceJobDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoDeleteModelInferenceJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
