// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoCancelModelInferenceJobParams creates a new KafeidoCancelModelInferenceJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoCancelModelInferenceJobParams() *KafeidoCancelModelInferenceJobParams {
	return &KafeidoCancelModelInferenceJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoCancelModelInferenceJobParamsWithTimeout creates a new KafeidoCancelModelInferenceJobParams object
// with the ability to set a timeout on a request.
func NewKafeidoCancelModelInferenceJobParamsWithTimeout(timeout time.Duration) *KafeidoCancelModelInferenceJobParams {
	return &KafeidoCancelModelInferenceJobParams{
		timeout: timeout,
	}
}

// NewKafeidoCancelModelInferenceJobParamsWithContext creates a new KafeidoCancelModelInferenceJobParams object
// with the ability to set a context for a request.
func NewKafeidoCancelModelInferenceJobParamsWithContext(ctx context.Context) *KafeidoCancelModelInferenceJobParams {
	return &KafeidoCancelModelInferenceJobParams{
		Context: ctx,
	}
}

// NewKafeidoCancelModelInferenceJobParamsWithHTTPClient creates a new KafeidoCancelModelInferenceJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoCancelModelInferenceJobParamsWithHTTPClient(client *http.Client) *KafeidoCancelModelInferenceJobParams {
	return &KafeidoCancelModelInferenceJobParams{
		HTTPClient: client,
	}
}

/*
KafeidoCancelModelInferenceJobParams contains all the parameters to send to the API endpoint

	for the kafeido cancel model inference job operation.

	Typically these are written to a http.Request.
*/
type KafeidoCancelModelInferenceJobParams struct {

	// Body.
	Body interface{}

	// ModelInferenceJobID.
	ModelInferenceJobID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido cancel model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCancelModelInferenceJobParams) WithDefaults() *KafeidoCancelModelInferenceJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido cancel model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCancelModelInferenceJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithTimeout(timeout time.Duration) *KafeidoCancelModelInferenceJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithContext(ctx context.Context) *KafeidoCancelModelInferenceJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithHTTPClient(client *http.Client) *KafeidoCancelModelInferenceJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithBody(body interface{}) *KafeidoCancelModelInferenceJobParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetBody(body interface{}) {
	o.Body = body
}

// WithModelInferenceJobID adds the modelInferenceJobID to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithModelInferenceJobID(modelInferenceJobID string) *KafeidoCancelModelInferenceJobParams {
	o.SetModelInferenceJobID(modelInferenceJobID)
	return o
}

// SetModelInferenceJobID adds the modelInferenceJobId to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetModelInferenceJobID(modelInferenceJobID string) {
	o.ModelInferenceJobID = modelInferenceJobID
}

// WithProjectID adds the projectID to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) WithProjectID(projectID string) *KafeidoCancelModelInferenceJobParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido cancel model inference job params
func (o *KafeidoCancelModelInferenceJobParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoCancelModelInferenceJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param modelInferenceJobId
	if err := r.SetPathParam("modelInferenceJobId", o.ModelInferenceJobID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
