// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoGetProjectParams creates a new KafeidoGetProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoGetProjectParams() *KafeidoGetProjectParams {
	return &KafeidoGetProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoGetProjectParamsWithTimeout creates a new KafeidoGetProjectParams object
// with the ability to set a timeout on a request.
func NewKafeidoGetProjectParamsWithTimeout(timeout time.Duration) *KafeidoGetProjectParams {
	return &KafeidoGetProjectParams{
		timeout: timeout,
	}
}

// NewKafeidoGetProjectParamsWithContext creates a new KafeidoGetProjectParams object
// with the ability to set a context for a request.
func NewKafeidoGetProjectParamsWithContext(ctx context.Context) *KafeidoGetProjectParams {
	return &KafeidoGetProjectParams{
		Context: ctx,
	}
}

// NewKafeidoGetProjectParamsWithHTTPClient creates a new KafeidoGetProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoGetProjectParamsWithHTTPClient(client *http.Client) *KafeidoGetProjectParams {
	return &KafeidoGetProjectParams{
		HTTPClient: client,
	}
}

/*
KafeidoGetProjectParams contains all the parameters to send to the API endpoint

	for the kafeido get project operation.

	Typically these are written to a http.Request.
*/
type KafeidoGetProjectParams struct {

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido get project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoGetProjectParams) WithDefaults() *KafeidoGetProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido get project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoGetProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido get project params
func (o *KafeidoGetProjectParams) WithTimeout(timeout time.Duration) *KafeidoGetProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido get project params
func (o *KafeidoGetProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido get project params
func (o *KafeidoGetProjectParams) WithContext(ctx context.Context) *KafeidoGetProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido get project params
func (o *KafeidoGetProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido get project params
func (o *KafeidoGetProjectParams) WithHTTPClient(client *http.Client) *KafeidoGetProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido get project params
func (o *KafeidoGetProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the kafeido get project params
func (o *KafeidoGetProjectParams) WithProjectID(projectID string) *KafeidoGetProjectParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido get project params
func (o *KafeidoGetProjectParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoGetProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
