// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoPutProjectParams creates a new KafeidoPutProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoPutProjectParams() *KafeidoPutProjectParams {
	return &KafeidoPutProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoPutProjectParamsWithTimeout creates a new KafeidoPutProjectParams object
// with the ability to set a timeout on a request.
func NewKafeidoPutProjectParamsWithTimeout(timeout time.Duration) *KafeidoPutProjectParams {
	return &KafeidoPutProjectParams{
		timeout: timeout,
	}
}

// NewKafeidoPutProjectParamsWithContext creates a new KafeidoPutProjectParams object
// with the ability to set a context for a request.
func NewKafeidoPutProjectParamsWithContext(ctx context.Context) *KafeidoPutProjectParams {
	return &KafeidoPutProjectParams{
		Context: ctx,
	}
}

// NewKafeidoPutProjectParamsWithHTTPClient creates a new KafeidoPutProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoPutProjectParamsWithHTTPClient(client *http.Client) *KafeidoPutProjectParams {
	return &KafeidoPutProjectParams{
		HTTPClient: client,
	}
}

/*
KafeidoPutProjectParams contains all the parameters to send to the API endpoint

	for the kafeido put project operation.

	Typically these are written to a http.Request.
*/
type KafeidoPutProjectParams struct {

	// Body.
	Body KafeidoPutProjectBody

	/* ProjectID.

	   given when a project has been created
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido put project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoPutProjectParams) WithDefaults() *KafeidoPutProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido put project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoPutProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido put project params
func (o *KafeidoPutProjectParams) WithTimeout(timeout time.Duration) *KafeidoPutProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido put project params
func (o *KafeidoPutProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido put project params
func (o *KafeidoPutProjectParams) WithContext(ctx context.Context) *KafeidoPutProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido put project params
func (o *KafeidoPutProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido put project params
func (o *KafeidoPutProjectParams) WithHTTPClient(client *http.Client) *KafeidoPutProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido put project params
func (o *KafeidoPutProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido put project params
func (o *KafeidoPutProjectParams) WithBody(body KafeidoPutProjectBody) *KafeidoPutProjectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido put project params
func (o *KafeidoPutProjectParams) SetBody(body KafeidoPutProjectBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido put project params
func (o *KafeidoPutProjectParams) WithProjectID(projectID string) *KafeidoPutProjectParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido put project params
func (o *KafeidoPutProjectParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoPutProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
