// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// NewKafeidoAppLoginParams creates a new KafeidoAppLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoAppLoginParams() *KafeidoAppLoginParams {
	return &KafeidoAppLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoAppLoginParamsWithTimeout creates a new KafeidoAppLoginParams object
// with the ability to set a timeout on a request.
func NewKafeidoAppLoginParamsWithTimeout(timeout time.Duration) *KafeidoAppLoginParams {
	return &KafeidoAppLoginParams{
		timeout: timeout,
	}
}

// NewKafeidoAppLoginParamsWithContext creates a new KafeidoAppLoginParams object
// with the ability to set a context for a request.
func NewKafeidoAppLoginParamsWithContext(ctx context.Context) *KafeidoAppLoginParams {
	return &KafeidoAppLoginParams{
		Context: ctx,
	}
}

// NewKafeidoAppLoginParamsWithHTTPClient creates a new KafeidoAppLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoAppLoginParamsWithHTTPClient(client *http.Client) *KafeidoAppLoginParams {
	return &KafeidoAppLoginParams{
		HTTPClient: client,
	}
}

/*
KafeidoAppLoginParams contains all the parameters to send to the API endpoint

	for the kafeido app login operation.

	Typically these are written to a http.Request.
*/
type KafeidoAppLoginParams struct {

	// Body.
	Body *models.KafeidoAppLoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido app login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoAppLoginParams) WithDefaults() *KafeidoAppLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido app login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoAppLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido app login params
func (o *KafeidoAppLoginParams) WithTimeout(timeout time.Duration) *KafeidoAppLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido app login params
func (o *KafeidoAppLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido app login params
func (o *KafeidoAppLoginParams) WithContext(ctx context.Context) *KafeidoAppLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido app login params
func (o *KafeidoAppLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido app login params
func (o *KafeidoAppLoginParams) WithHTTPClient(client *http.Client) *KafeidoAppLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido app login params
func (o *KafeidoAppLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido app login params
func (o *KafeidoAppLoginParams) WithBody(body *models.KafeidoAppLoginRequest) *KafeidoAppLoginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido app login params
func (o *KafeidoAppLoginParams) SetBody(body *models.KafeidoAppLoginRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoAppLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
