// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoDeleteProjectPipelineParams creates a new KafeidoDeleteProjectPipelineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoDeleteProjectPipelineParams() *KafeidoDeleteProjectPipelineParams {
	return &KafeidoDeleteProjectPipelineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoDeleteProjectPipelineParamsWithTimeout creates a new KafeidoDeleteProjectPipelineParams object
// with the ability to set a timeout on a request.
func NewKafeidoDeleteProjectPipelineParamsWithTimeout(timeout time.Duration) *KafeidoDeleteProjectPipelineParams {
	return &KafeidoDeleteProjectPipelineParams{
		timeout: timeout,
	}
}

// NewKafeidoDeleteProjectPipelineParamsWithContext creates a new KafeidoDeleteProjectPipelineParams object
// with the ability to set a context for a request.
func NewKafeidoDeleteProjectPipelineParamsWithContext(ctx context.Context) *KafeidoDeleteProjectPipelineParams {
	return &KafeidoDeleteProjectPipelineParams{
		Context: ctx,
	}
}

// NewKafeidoDeleteProjectPipelineParamsWithHTTPClient creates a new KafeidoDeleteProjectPipelineParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoDeleteProjectPipelineParamsWithHTTPClient(client *http.Client) *KafeidoDeleteProjectPipelineParams {
	return &KafeidoDeleteProjectPipelineParams{
		HTTPClient: client,
	}
}

/*
KafeidoDeleteProjectPipelineParams contains all the parameters to send to the API endpoint

	for the kafeido delete project pipeline operation.

	Typically these are written to a http.Request.
*/
type KafeidoDeleteProjectPipelineParams struct {

	// NamedPipelineID.
	NamedPipelineID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido delete project pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoDeleteProjectPipelineParams) WithDefaults() *KafeidoDeleteProjectPipelineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido delete project pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoDeleteProjectPipelineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) WithTimeout(timeout time.Duration) *KafeidoDeleteProjectPipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) WithContext(ctx context.Context) *KafeidoDeleteProjectPipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) WithHTTPClient(client *http.Client) *KafeidoDeleteProjectPipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamedPipelineID adds the namedPipelineID to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) WithNamedPipelineID(namedPipelineID string) *KafeidoDeleteProjectPipelineParams {
	o.SetNamedPipelineID(namedPipelineID)
	return o
}

// SetNamedPipelineID adds the namedPipelineId to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) SetNamedPipelineID(namedPipelineID string) {
	o.NamedPipelineID = namedPipelineID
}

// WithProjectID adds the projectID to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) WithProjectID(projectID string) *KafeidoDeleteProjectPipelineParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido delete project pipeline params
func (o *KafeidoDeleteProjectPipelineParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoDeleteProjectPipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namedPipelineId
	if err := r.SetPathParam("namedPipelineId", o.NamedPipelineID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
