// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoCreateProjectReader is a Reader for the KafeidoCreateProject structure.
type KafeidoCreateProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoCreateProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoCreateProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoCreateProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoCreateProjectOK creates a KafeidoCreateProjectOK with default headers values
func NewKafeidoCreateProjectOK() *KafeidoCreateProjectOK {
	return &KafeidoCreateProjectOK{}
}

/*
KafeidoCreateProjectOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoCreateProjectOK struct {
	Payload *models.KafeidoCreateProjectResponse
}

// IsSuccess returns true when this kafeido create project o k response has a 2xx status code
func (o *KafeidoCreateProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido create project o k response has a 3xx status code
func (o *KafeidoCreateProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido create project o k response has a 4xx status code
func (o *KafeidoCreateProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido create project o k response has a 5xx status code
func (o *KafeidoCreateProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido create project o k response a status code equal to that given
func (o *KafeidoCreateProjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido create project o k response
func (o *KafeidoCreateProjectOK) Code() int {
	return 200
}

func (o *KafeidoCreateProjectOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects][%d] kafeidoCreateProjectOK  %+v", 200, o.Payload)
}

func (o *KafeidoCreateProjectOK) String() string {
	return fmt.Sprintf("[POST /v1/projects][%d] kafeidoCreateProjectOK  %+v", 200, o.Payload)
}

func (o *KafeidoCreateProjectOK) GetPayload() *models.KafeidoCreateProjectResponse {
	return o.Payload
}

func (o *KafeidoCreateProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KafeidoCreateProjectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoCreateProjectDefault creates a KafeidoCreateProjectDefault with default headers values
func NewKafeidoCreateProjectDefault(code int) *KafeidoCreateProjectDefault {
	return &KafeidoCreateProjectDefault{
		_statusCode: code,
	}
}

/*
KafeidoCreateProjectDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoCreateProjectDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido create project default response has a 2xx status code
func (o *KafeidoCreateProjectDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido create project default response has a 3xx status code
func (o *KafeidoCreateProjectDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido create project default response has a 4xx status code
func (o *KafeidoCreateProjectDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido create project default response has a 5xx status code
func (o *KafeidoCreateProjectDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido create project default response a status code equal to that given
func (o *KafeidoCreateProjectDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido create project default response
func (o *KafeidoCreateProjectDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoCreateProjectDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects][%d] kafeido_CreateProject default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCreateProjectDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects][%d] kafeido_CreateProject default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCreateProjectDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoCreateProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
