// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoListModelInferenceParams creates a new KafeidoListModelInferenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoListModelInferenceParams() *KafeidoListModelInferenceParams {
	return &KafeidoListModelInferenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoListModelInferenceParamsWithTimeout creates a new KafeidoListModelInferenceParams object
// with the ability to set a timeout on a request.
func NewKafeidoListModelInferenceParamsWithTimeout(timeout time.Duration) *KafeidoListModelInferenceParams {
	return &KafeidoListModelInferenceParams{
		timeout: timeout,
	}
}

// NewKafeidoListModelInferenceParamsWithContext creates a new KafeidoListModelInferenceParams object
// with the ability to set a context for a request.
func NewKafeidoListModelInferenceParamsWithContext(ctx context.Context) *KafeidoListModelInferenceParams {
	return &KafeidoListModelInferenceParams{
		Context: ctx,
	}
}

// NewKafeidoListModelInferenceParamsWithHTTPClient creates a new KafeidoListModelInferenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoListModelInferenceParamsWithHTTPClient(client *http.Client) *KafeidoListModelInferenceParams {
	return &KafeidoListModelInferenceParams{
		HTTPClient: client,
	}
}

/*
KafeidoListModelInferenceParams contains all the parameters to send to the API endpoint

	for the kafeido list model inference operation.

	Typically these are written to a http.Request.
*/
type KafeidoListModelInferenceParams struct {

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido list model inference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListModelInferenceParams) WithDefaults() *KafeidoListModelInferenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido list model inference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListModelInferenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) WithTimeout(timeout time.Duration) *KafeidoListModelInferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) WithContext(ctx context.Context) *KafeidoListModelInferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) WithHTTPClient(client *http.Client) *KafeidoListModelInferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) WithProjectID(projectID string) *KafeidoListModelInferenceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido list model inference params
func (o *KafeidoListModelInferenceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoListModelInferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
