// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoDeleteProjectParams creates a new KafeidoDeleteProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoDeleteProjectParams() *KafeidoDeleteProjectParams {
	return &KafeidoDeleteProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoDeleteProjectParamsWithTimeout creates a new KafeidoDeleteProjectParams object
// with the ability to set a timeout on a request.
func NewKafeidoDeleteProjectParamsWithTimeout(timeout time.Duration) *KafeidoDeleteProjectParams {
	return &KafeidoDeleteProjectParams{
		timeout: timeout,
	}
}

// NewKafeidoDeleteProjectParamsWithContext creates a new KafeidoDeleteProjectParams object
// with the ability to set a context for a request.
func NewKafeidoDeleteProjectParamsWithContext(ctx context.Context) *KafeidoDeleteProjectParams {
	return &KafeidoDeleteProjectParams{
		Context: ctx,
	}
}

// NewKafeidoDeleteProjectParamsWithHTTPClient creates a new KafeidoDeleteProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoDeleteProjectParamsWithHTTPClient(client *http.Client) *KafeidoDeleteProjectParams {
	return &KafeidoDeleteProjectParams{
		HTTPClient: client,
	}
}

/*
KafeidoDeleteProjectParams contains all the parameters to send to the API endpoint

	for the kafeido delete project operation.

	Typically these are written to a http.Request.
*/
type KafeidoDeleteProjectParams struct {

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido delete project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoDeleteProjectParams) WithDefaults() *KafeidoDeleteProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido delete project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoDeleteProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) WithTimeout(timeout time.Duration) *KafeidoDeleteProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) WithContext(ctx context.Context) *KafeidoDeleteProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) WithHTTPClient(client *http.Client) *KafeidoDeleteProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) WithProjectID(projectID string) *KafeidoDeleteProjectParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido delete project params
func (o *KafeidoDeleteProjectParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoDeleteProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
