// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/footprintai/grandturks-client/v2/api/app/kafeido/proto/go-openapiv2/models"
)

// KafeidoCancelModelInferenceJobReader is a Reader for the KafeidoCancelModelInferenceJob structure.
type KafeidoCancelModelInferenceJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KafeidoCancelModelInferenceJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKafeidoCancelModelInferenceJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewKafeidoCancelModelInferenceJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewKafeidoCancelModelInferenceJobOK creates a KafeidoCancelModelInferenceJobOK with default headers values
func NewKafeidoCancelModelInferenceJobOK() *KafeidoCancelModelInferenceJobOK {
	return &KafeidoCancelModelInferenceJobOK{}
}

/*
KafeidoCancelModelInferenceJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type KafeidoCancelModelInferenceJobOK struct {
	Payload models.KafeidoCancelModelInferenceJobResponse
}

// IsSuccess returns true when this kafeido cancel model inference job o k response has a 2xx status code
func (o *KafeidoCancelModelInferenceJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kafeido cancel model inference job o k response has a 3xx status code
func (o *KafeidoCancelModelInferenceJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kafeido cancel model inference job o k response has a 4xx status code
func (o *KafeidoCancelModelInferenceJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kafeido cancel model inference job o k response has a 5xx status code
func (o *KafeidoCancelModelInferenceJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kafeido cancel model inference job o k response a status code equal to that given
func (o *KafeidoCancelModelInferenceJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kafeido cancel model inference job o k response
func (o *KafeidoCancelModelInferenceJobOK) Code() int {
	return 200
}

func (o *KafeidoCancelModelInferenceJobOK) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/job/{modelInferenceJobId}:cancel][%d] kafeidoCancelModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoCancelModelInferenceJobOK) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/job/{modelInferenceJobId}:cancel][%d] kafeidoCancelModelInferenceJobOK  %+v", 200, o.Payload)
}

func (o *KafeidoCancelModelInferenceJobOK) GetPayload() models.KafeidoCancelModelInferenceJobResponse {
	return o.Payload
}

func (o *KafeidoCancelModelInferenceJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKafeidoCancelModelInferenceJobDefault creates a KafeidoCancelModelInferenceJobDefault with default headers values
func NewKafeidoCancelModelInferenceJobDefault(code int) *KafeidoCancelModelInferenceJobDefault {
	return &KafeidoCancelModelInferenceJobDefault{
		_statusCode: code,
	}
}

/*
KafeidoCancelModelInferenceJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type KafeidoCancelModelInferenceJobDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this kafeido cancel model inference job default response has a 2xx status code
func (o *KafeidoCancelModelInferenceJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this kafeido cancel model inference job default response has a 3xx status code
func (o *KafeidoCancelModelInferenceJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this kafeido cancel model inference job default response has a 4xx status code
func (o *KafeidoCancelModelInferenceJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this kafeido cancel model inference job default response has a 5xx status code
func (o *KafeidoCancelModelInferenceJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this kafeido cancel model inference job default response a status code equal to that given
func (o *KafeidoCancelModelInferenceJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the kafeido cancel model inference job default response
func (o *KafeidoCancelModelInferenceJobDefault) Code() int {
	return o._statusCode
}

func (o *KafeidoCancelModelInferenceJobDefault) Error() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/job/{modelInferenceJobId}:cancel][%d] kafeido_CancelModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCancelModelInferenceJobDefault) String() string {
	return fmt.Sprintf("[POST /v1/projects/{projectId}/job/{modelInferenceJobId}:cancel][%d] kafeido_CancelModelInferenceJob default  %+v", o._statusCode, o.Payload)
}

func (o *KafeidoCancelModelInferenceJobDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *KafeidoCancelModelInferenceJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
