// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoListModelInferenceJobParams creates a new KafeidoListModelInferenceJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoListModelInferenceJobParams() *KafeidoListModelInferenceJobParams {
	return &KafeidoListModelInferenceJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoListModelInferenceJobParamsWithTimeout creates a new KafeidoListModelInferenceJobParams object
// with the ability to set a timeout on a request.
func NewKafeidoListModelInferenceJobParamsWithTimeout(timeout time.Duration) *KafeidoListModelInferenceJobParams {
	return &KafeidoListModelInferenceJobParams{
		timeout: timeout,
	}
}

// NewKafeidoListModelInferenceJobParamsWithContext creates a new KafeidoListModelInferenceJobParams object
// with the ability to set a context for a request.
func NewKafeidoListModelInferenceJobParamsWithContext(ctx context.Context) *KafeidoListModelInferenceJobParams {
	return &KafeidoListModelInferenceJobParams{
		Context: ctx,
	}
}

// NewKafeidoListModelInferenceJobParamsWithHTTPClient creates a new KafeidoListModelInferenceJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoListModelInferenceJobParamsWithHTTPClient(client *http.Client) *KafeidoListModelInferenceJobParams {
	return &KafeidoListModelInferenceJobParams{
		HTTPClient: client,
	}
}

/*
KafeidoListModelInferenceJobParams contains all the parameters to send to the API endpoint

	for the kafeido list model inference job operation.

	Typically these are written to a http.Request.
*/
type KafeidoListModelInferenceJobParams struct {

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido list model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListModelInferenceJobParams) WithDefaults() *KafeidoListModelInferenceJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido list model inference job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListModelInferenceJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) WithTimeout(timeout time.Duration) *KafeidoListModelInferenceJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) WithContext(ctx context.Context) *KafeidoListModelInferenceJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) WithHTTPClient(client *http.Client) *KafeidoListModelInferenceJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) WithProjectID(projectID string) *KafeidoListModelInferenceJobParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido list model inference job params
func (o *KafeidoListModelInferenceJobParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoListModelInferenceJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
