// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoListDataSourceParams creates a new KafeidoListDataSourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoListDataSourceParams() *KafeidoListDataSourceParams {
	return &KafeidoListDataSourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoListDataSourceParamsWithTimeout creates a new KafeidoListDataSourceParams object
// with the ability to set a timeout on a request.
func NewKafeidoListDataSourceParamsWithTimeout(timeout time.Duration) *KafeidoListDataSourceParams {
	return &KafeidoListDataSourceParams{
		timeout: timeout,
	}
}

// NewKafeidoListDataSourceParamsWithContext creates a new KafeidoListDataSourceParams object
// with the ability to set a context for a request.
func NewKafeidoListDataSourceParamsWithContext(ctx context.Context) *KafeidoListDataSourceParams {
	return &KafeidoListDataSourceParams{
		Context: ctx,
	}
}

// NewKafeidoListDataSourceParamsWithHTTPClient creates a new KafeidoListDataSourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoListDataSourceParamsWithHTTPClient(client *http.Client) *KafeidoListDataSourceParams {
	return &KafeidoListDataSourceParams{
		HTTPClient: client,
	}
}

/*
KafeidoListDataSourceParams contains all the parameters to send to the API endpoint

	for the kafeido list data source operation.

	Typically these are written to a http.Request.
*/
type KafeidoListDataSourceParams struct {

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido list data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListDataSourceParams) WithDefaults() *KafeidoListDataSourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido list data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoListDataSourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido list data source params
func (o *KafeidoListDataSourceParams) WithTimeout(timeout time.Duration) *KafeidoListDataSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido list data source params
func (o *KafeidoListDataSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido list data source params
func (o *KafeidoListDataSourceParams) WithContext(ctx context.Context) *KafeidoListDataSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido list data source params
func (o *KafeidoListDataSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido list data source params
func (o *KafeidoListDataSourceParams) WithHTTPClient(client *http.Client) *KafeidoListDataSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido list data source params
func (o *KafeidoListDataSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the kafeido list data source params
func (o *KafeidoListDataSourceParams) WithProjectID(projectID string) *KafeidoListDataSourceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido list data source params
func (o *KafeidoListDataSourceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoListDataSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
