// Code generated by go-swagger; DO NOT EDIT.

package kafeido

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKafeidoCreateDataSourceParams creates a new KafeidoCreateDataSourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKafeidoCreateDataSourceParams() *KafeidoCreateDataSourceParams {
	return &KafeidoCreateDataSourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewKafeidoCreateDataSourceParamsWithTimeout creates a new KafeidoCreateDataSourceParams object
// with the ability to set a timeout on a request.
func NewKafeidoCreateDataSourceParamsWithTimeout(timeout time.Duration) *KafeidoCreateDataSourceParams {
	return &KafeidoCreateDataSourceParams{
		timeout: timeout,
	}
}

// NewKafeidoCreateDataSourceParamsWithContext creates a new KafeidoCreateDataSourceParams object
// with the ability to set a context for a request.
func NewKafeidoCreateDataSourceParamsWithContext(ctx context.Context) *KafeidoCreateDataSourceParams {
	return &KafeidoCreateDataSourceParams{
		Context: ctx,
	}
}

// NewKafeidoCreateDataSourceParamsWithHTTPClient creates a new KafeidoCreateDataSourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewKafeidoCreateDataSourceParamsWithHTTPClient(client *http.Client) *KafeidoCreateDataSourceParams {
	return &KafeidoCreateDataSourceParams{
		HTTPClient: client,
	}
}

/*
KafeidoCreateDataSourceParams contains all the parameters to send to the API endpoint

	for the kafeido create data source operation.

	Typically these are written to a http.Request.
*/
type KafeidoCreateDataSourceParams struct {

	// Body.
	Body KafeidoCreateDataSourceBody

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kafeido create data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCreateDataSourceParams) WithDefaults() *KafeidoCreateDataSourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kafeido create data source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KafeidoCreateDataSourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) WithTimeout(timeout time.Duration) *KafeidoCreateDataSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) WithContext(ctx context.Context) *KafeidoCreateDataSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) WithHTTPClient(client *http.Client) *KafeidoCreateDataSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) WithBody(body KafeidoCreateDataSourceBody) *KafeidoCreateDataSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) SetBody(body KafeidoCreateDataSourceBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) WithProjectID(projectID string) *KafeidoCreateDataSourceParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the kafeido create data source params
func (o *KafeidoCreateDataSourceParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *KafeidoCreateDataSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
